"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xd35&07be+c0f7#@6qil*i-!!%m-*cv0_d@68nqmacoklhg8bx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'oauth2_provider',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
import os
# OAuth2 specific settings
OAUTH2_PROVIDER = {
    'OIDC_ENABLED': True,
    'OIDC_RSA_PRIVATE_KEY': """-----BEGIN RSA PRIVATE KEY-----
MIIJKQIBAAKCAgEApC/CLEpnpJTP9VQwmDXb2Q7DLca0kJnY6FxajuCma/IahSBi
FAioKe2vcO+55Mf5MHlu5CBJUeL5yNgBe5blHUVzFDw6mx4nVKaGRBSsCqtY78hy
nKg8IbTse4SeNM3r0/Ovemq5tHBpWqLmLEmsadJ1omRKvtc/o8LbBc+InodZHwg+
HmvPax0wqw8mpkJevisWot3fFmgTEZfY84ka8Luu5njmTSs+7L2OjBL0QpUtr/ox
+fLTs2NoIZwmH3sS66vD/3dR1QMZ9mqdaTXUdSd/45s3P1mD+xFm9tYFFv6xiBXD
RKzVC3r7gzg39Dz1F2h7IDBpK+qcXZNX98UalfCE1SAW8R1ekCRmipoGD+Fce42e
+qUrlHRimD9mkG7k3lMr1ZHaXCzLofWFoYyxB3FLUcDxyyjaz7HIKDmPbRvR7Qqj
nt+848a9HcyCOlQP1jiU33VVSOS2IxVUHTB5voehW2HC72pRIckf6tGTBTcfXakW
QMADpo2x+xisIgA3cxIn/j63uzMMg9dZ3ipKMdlE1rpZA0jeBd5OYurEGiLVX/vC
LGji7fv2Tq3y0rdbKgtghdYir0No2mbQZDGpWbf+fFJdnyOQaaW52jNEWqp36i+w
z7rX3fjRF2/fnzepQTx8TgMbOXKIZA9skqVTfItz1G3rXh+i0iXEZRptAhMCAwEA
AQKCAgEAiH772n5w866TxM0dKS19fFJ9iQztCFoere45ixbQxGUeDxcA8s7Pnyvu
8uEZlk15qQcLXbRJwD4Gkyag9PJZv6ABMA1yW4sR/5oBfZACB0y0P4RRZFOoygzz
nSx/qj6XlDm+5PLdOFlL/QH4gVEueTtyeHMQgN/KFIbmN0p1tfWn7diYbAoNAmve
DhgmdYov4cFIrFXwJVyYncOzpaOSNhiSKyDPtdACHCbq3yDS2JfUx7wk2Ds8LKKz
6105hGp5LFw8MaIs8f4GE4pHGzSZUFxqQfrET3JH+u5Yv1TmHlvXk98j23AkHcs8
VbbjLbWPvMorsnMMvGnrXRAlzeKbWj8cYWN7MkDoYVe095aGdJu7KJZlJ/88V6qI
gVXeQsPZmYBQbyxK+N+jRItQeiHZE1xT3w6g+QjsSnEAOyfA4ghYXchQLzqqOMjt
ErrhnX4WmpG4Y51bLod3vFc0tFU7lqWuGpS1jAHimsaXpkKYVVGQUCHwWKo7zwop
wGO1VpZ7oeVJTIH0hCh0MGkow0a1/254qCdWsdFX1uuOeCcEKy6rGyERHD23/qNa
eHJuIphwYwBfOOAHQEGeEwFohTepKHIGDQm3iOMtXpxWaBLTzS+tgtritWOdTtfU
h8ZaNYmfNkFISzHgUJTyKu6kgwgg5Rj9aD24KENFHm7tRYgtQSECggEBAM0ZdFt5
xeYXPnFr5mvtnhHL1u8wwVbc2Mk6jHvc9LuNIbtHnODx+eySP6Jk6XKHmcImPXle
TY/0TGjaLAkgwru28/8X5j5CwBEVxVO17RnF4YZg1/htHuiKDFJXwzLAtxK0vTg/
E2tUsrrFr1K2Qz76x4qMxZkfFy0c4DvGxKF6QcRwVe5NPJJX+Pwxh9o6Usds79gF
dvKLFnN+63k305UnlLA3UY9gHxtzKo+dhJ+Hbjr6eOTOqli2wauLRdFs6UFC/5Xf
jrceUtSKx1FPDkwbr+rj8ZBPoHXgGwPj9cei0zqaXQuseL84ZkjAkCXNS+2Wm1cB
8pR5PCfiGLzKE+0CggEBAMzu/lxSCfybyjWInky9XtY89+ipIiYyz0H7Ry5Pn8mw
C7WPFbE3mN/OwxEUQGhoNxkrE9q33Ayv6vMGsvwSE0ykS1fSzd+8iwbplD0WFk/A
c77WigHwqN+EzMXMzbf1On8lHOYsevZw60g6aMefWz+Xi2CFtb23bbAxOAs8Lz/K
95mh2PBj2anuhPeRwOYcgo+Y1X/Kyz4DzyGPyspLSutSOAU/897ilU/+/3I4Q0Fe
I5gBMYBkMy9NsYO3NTEM+5DYUosxFqHBTLFlyFtLzzMZ9w7HCk2z7Qv+bQszaCpB
ogwJ1vt5ytfy5xZYLaqGv3vQxndE9XXcnUimYRbcrf8CggEAWiCIaDY/x5eJQhA3
RlA5uPpJLfzPyRrtTKgk2b1D8jLXktOqVZMfz1yJCBSuHT0HTTC+rNnK3apt9VmC
JlS2HgUMfZmD/PIaMqfNebalRUEWlJVz8mAJSAh516lnRqM3D8pKqC/Xmb+zdq2u
GHutWzyaeQDZSCtIZPOeecYj3A28XtU6faiFKI3uBOzDFRuyCp6NWvEzzutd50zr
ru3gVVf6V+FHPujvYoGeP1Pp1qyNvO8aNvm2E5vjyT0/ZgMlER+e7r45mbCCl5GQ
euNxlfJIwMCAA3lqOsJLPM9szth3V/ZDUwDsYqMnF2s/LM1lQzd+daKOdb48uA37
7uIiFQKCAQEAnLsjmeO8c4+KZMrplnM2Ns9GIpBH58LwM9xDoi2PXSbgraiSxIhq
yLBPC57ba35YtUz20E3RY3qfS+KRvKruS61TWgWFIloGUfEOSHG9+pyLaSaXQciW
vuvH2Hc71jcc1+TAZ2EZYaUWrJTPUeyUUtxJ4jYgusmwgBIEdMNAt585Iixfx+n1
rDsZQmYci2C+kagnkKa+Ld2n6lkYlQJkd/jXk1xH3OyZmSbCos5Y0YN34Wb4PuNj
KghXfQ7/BVaSh0KKTp3qWyeEyh+3zer6unBfPNQJE0hKQOQC7ZARWE/96QsVehq5
gdLp3XLu6f5IMB+JyenZeJyTRd7JXjzEbQKCAQBpZSzYzmjTT+WoFC8jB/vSYAB8
XLH4Me6s/NFarUxwFa3Q9UMBFOhVtpCchAQkUIdvD5sCykk0XjDAvHvWAZPE3pX8
xIH4x5kkO92YgmPHl2+mGSbHVlllHD5E9kuNGqRyVrIfvRcU4L5f9kTyCkCvLGFV
qePUacc5MDU8NzDj2Ic8Bt1F2ai0LqcFfEHVczO3urVS0djhk54K8FKS+/wXMTZN
Y956ZXCQDGYsSf/Swyi4cGE6r/VwqRQwmAWe4E29TRHd4cKuPu2DVBvn96MP31ht
JDKrpOWOzPBiodqB2LQTxGE6tQjt+BHXn2gq25mUf165biNCH0EyKvXxQzIb
-----END RSA PRIVATE KEY-----
""",
    'SCOPES': {
        'openid': "OpenID Connect scope"
    },
    "OIDC_RP_INITIATED_LOGOUT_ENABLED": True,
    "OIDC_RP_INITIATED_LOGOUT_ALWAYS_PROMPT": True,
}

ALLOWED_HOSTS = ['*']
LOGIN_URL = "/admin/login/"
